# Generated by Django 4.2.7 on 2023-11-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=64)),
                ('imagen', models.CharField(max_length=256)),
                ('estrellas', models.IntegerField(default=0)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16, unique=True)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('precioser', models.FloatField(default=0)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('correo_electronico', models.CharField(max_length=64, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('contrasena', models.CharField(max_length=16)),
                ('hab', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cvd', models.IntegerField()),
                ('hab', models.BooleanField(default=True)),
                ('clvusu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clvemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('clvser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='clvemp',
            field=models.ManyToManyField(through='api.ServicoEmpleado', to='api.empleado'),
        ),
        migrations.CreateModel(
            name='Pestanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('foto', models.CharField(default='https://images.squarespace-cdn.com/content/v1/5b9d43fb55b02cec87e4c0ad/1539988476944-U5ZT074DKC5AYSYGXHSY/Screen+Shot+2018-10-19+at+5.32.01+PM.png', max_length=256)),
                ('preciopes', models.FloatField(default=0)),
                ('hab', models.BooleanField(default=True)),
                ('clvtip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='clvpst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puesto'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio_final', models.FloatField(default=0)),
                ('hab', models.BooleanField(default=True)),
                ('clvfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapago')),
                ('clvpes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pestanas')),
                ('clvser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
                ('clvstat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estatus')),
                ('clvusu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
