# Generated by Django 4.2.7 on 2023-11-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pestanas_tamano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=32)),
                ('destino', models.CharField(max_length=64)),
                ('estrellas', models.PositiveIntegerField(default=1)),
                ('comentario', models.CharField(max_length=256)),
            ],
        ),
    ]
