# Generated by Django 4.2.7 on 2023-11-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='clvuser',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
