# Generated by Django 4.2.7 on 2023-11-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resena_clvuser_resena_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='clvemp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empleado'),
        ),
    ]
